baseurl: "/IMA.js-core"
exclude: ["_partials"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "doc"